/* tslint:disable */

export class GtfsMock {

  constructor () {}

  UM_Transit = {
    routes: [
      {
        "route_long_name": "Commuter North",
        "route_type": 3,
        "route_text_color": "000000",
        "route_color": "00FFFF",
        "agency_id": "UM_Transit",
        "route_id": "CN",
        "route_url": "http://ltp.umich.edu/maps/commuter_northbound.pdf",
        "route_desc": "The Commuter North begins at Crisler Center and ends at Glazier Way, connecting South Campus with North Campus via Central Campus, the Hill area, and the Medical Campus, and serving destinations including the Michigan Union, Central Campus Transit Center, University of Michigan Hospitals, and Pierpont Commons. Routing varies before 7:00 AM and after 7:30 PM, and during Ann Arbor Art Fair; check our website for details.",
        "route_short_name": "CN"
      },
      {
        "route_long_name": "Bursley Baits",
        "route_type": 3,
        "route_text_color": "000000",
        "route_color": "FF00FF",
        "agency_id": "UM_Transit",
        "route_id": "BB",
        "route_url": "http://ltp.umich.edu/maps/bursley_baits.pdf",
        "route_desc": "Bursley-Baits provides service between the Central Campus Transit Center, Bursley Hall and Vera Baits Houses on North Campus. Bursley-Baits operates seven days per week during Fall and Winter terms only. The evening and weekend Bursley-Baits route also provides outbound service to Stockwell Hall and the Cardiovascular Center along Observatory.",
        "route_short_name": "BB"
      },
      {
        "route_long_name": "Diag-to-Diag Express",
        "route_type": 3,
        "route_text_color": "000000",
        "route_color": "0000FF",
        "agency_id": "UM_Transit",
        "route_id": "DD",
        "route_url": "http://ltp.umich.edu/maps/diag_diag.pdf",
        "route_desc": "Diag to Diag provides service between Cooley Lab via Pierpont Commons to the Central Campus Transit Center (and continuing to Oxford Housing). Diag to Diag operates on a limited schedule Monday through Friday during Fall and Winter terms. Check our website for details.",
        "route_short_name": "DD"
      },
      {
        "route_long_name": "North-East Shuttle",
        "route_type": 3,
        "route_text_color": "000000",
        "route_color": "008000",
        "agency_id": "UM_Transit",
        "route_id": "NE",
        "route_url": "http://ltp.umich.edu/maps/north_east_shuttle.pdf",
        "route_desc": "The North-East Shuttle connects the Medical Campus to the VA Hospital, North Campus Research Complex, and East Campus destinations including the Green Rd Park-and-Ride, Plymouth Rd Park-and-Ride, East Medical Campus, and Dominos Farms.",
        "route_short_name": "NES"
      },
      {
        "route_long_name": "Northwood Express",
        "route_type": 3,
        "route_text_color": "000000",
        "route_color": "C0C0C0",
        "agency_id": "UM_Transit",
        "route_id": "NX",
        "route_url": "http://ltp.umich.edu/maps/northwood_express.pdf",
        "route_desc": "Northwood Express provides service between the North Campus Fire Station through Northwood Housing areas to the Central Campus Transit Center (and continuing to Oxford Housing). Northwood Express operates on a limited schedule Monday through Friday during Fall and Winter terms. Check our website for details.",
        "route_short_name": "NX"
      },
      {
        "route_long_name": "Wall Street-NIB",
        "route_type": 3,
        "route_text_color": "000000",
        "route_color": "FF88FF",
        "agency_id": "UM_Transit",
        "route_id": "WS",
        "route_url": "http://ltp.umich.edu/maps/wall_street.pdf",
        "route_desc": "Wall Street-NIB provides service between the Wall St parking structure and the North Ingalls building, via Medical Campus destinations.",
        "route_short_name": "WSN"
      },
      {
        "route_long_name": "Crisler Express",
        "route_type": 3,
        "route_text_color": "000000",
        "route_color": "FFA3A3",
        "agency_id": "UM_Transit",
        "route_id": "CSX",
        "route_url": "http://ltp.umich.edu/maps/crisler_express.pdf",
        "route_desc": "The Crisler Express begins at the Cancer Center and ends at lot SC-7. After leaving the BSRB, the route heads directly towards South Campus parking lots (SC-5, SC-6, and SC-7). The first pick up is at 3:45 PM and the last pick up is at 6:45 PM (20 minute frequency). Check our website for details.",
        "route_short_name": "CE"
      },
      {
        "route_long_name": "Commuter South",
        "route_type": 3,
        "route_text_color": "000000",
        "route_color": "00FF00",
        "agency_id": "UM_Transit",
        "route_id": "CS",
        "route_url": "http://ltp.umich.edu/maps/commuter_southbound.pdf",
        "route_desc": "The Commuter South begins at Glazier Way and ends at Crisler Center, connecting North Campus with South Campus via the Medical Campus, the Hill area, and Central Campus, and serving destinations including Pierpont Commons, University of Michigan Hospitals, Central Campus Transit Center, and the Michigan Union. Routing varies before 7:00 AM and after 7:30 PM, and during Ann Arbor Art Fair; check our website for details.",
        "route_short_name": "CS"
      },
      {
        "route_long_name": "Northwood",
        "route_type": 3,
        "route_text_color": "000000",
        "route_color": "FF8040",
        "agency_id": "UM_Transit",
        "route_id": "NW",
        "route_url": "http://ltp.umich.edu/maps/northwood.pdf",
        "route_desc": "Northwood services Central Campus and Northwood Housing areas on North Campus. It operates 7 days a week, year round, except for University holidays. During the spring and summer terms there are weekend service gaps; check our website for details.",
        "route_short_name": "NW"
      },
      {
        "route_long_name": "Oxford Shuttle",
        "route_type": 3,
        "route_text_color": "000000",
        "route_color": "C0C0C0",
        "agency_id": "UM_Transit",
        "route_id": "OS",
        "route_url": "http://ltp.umich.edu/maps/oxford_shuttle.pdf",
        "route_desc": "Oxford Shuttle provides service between Oxford Housing, Trotter House, Shapiro Undergraduate Library, Michigan Union, the Central Campus Transit Center, and East Quadrangle. Oxford Shuttle operates weeknights and weekends only.",
        "route_short_name": "OS"
      },
      {
        "route_long_name": "Med Express",
        "route_type": 3,
        "route_text_color": "000000",
        "route_color": "A6CAF0",
        "agency_id": "UM_Transit",
        "route_id": "MX",
        "route_url": "http://ltp.umich.edu/maps/med_express.pdf",
        "route_desc": "MedExpress connects Glazier Way (NC51) Lot and Orange Fuller Road lots to Medical Campus locations: Cancer Center, Taubman Center/University Hospital and Mott Children's Hospital/M22. Trips prior to 7:00 AM enter the M75 Mitchell Field lot. Return trips should be made on Commuter North.",
        "route_short_name": "ME"
      },
      {
        "route_long_name": "Wall Street Express",
        "route_type": 3,
        "route_text_color": "000000",
        "route_color": "FF2B95",
        "agency_id": "UM_Transit",
        "route_id": "WX",
        "route_url": "http://ltp.umich.edu/maps/wall_street.pdf",
        "route_desc": "Wall Street Express provides service between the Wall St parking structure across from Kellog Eye Center to Medical Campus destinations.",
        "route_short_name": "WSE"
      }
    ],
    trips: [{
      "route_id": "NE",
      "service_id": 5,
      "trip_id": 43415,
      "trip_headsign": "NorthEast Shuttle to Dominos Farm",
      "trip_short_name": "",
      "direction_id": 0,
      "block_id": 3725,
      "shape_id": 750,
      "wheelchair_accessible": 1,
      "bikes_allowed": 2
      },
      {
        "route_id": "CN",
        "service_id": 3705,
        "trip_id": 42392,
        "trip_headsign": "Commuter North to Glazier Way",
        "trip_short_name": "",
        "direction_id": 0,
        "block_id": 3516,
        "shape_id": 739,
        "wheelchair_accessible": 1,
        "bikes_allowed": 2
      },
      {
        "route_id": "CS",
        "service_id": 3705,
        "trip_id": 42559,
        "trip_headsign": "Commuter South to Kipke Drive",
        "trip_short_name": "",
        "direction_id": 1,
        "block_id": 3601,
        "shape_id": 740,
        "wheelchair_accessible": 1,
        "bikes_allowed": 2
      }
    ],
    stops:  [
      {
        "stop_id": "C200",
        "stop_code": "C200",
        "stop_name": "Michigan Union, S. State",
        "stop_desc": "across from Michigan Union at Art Museum",
        "stop_lat": 42.275151,
        "stop_lon": -83.740607,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "C201",
        "stop_code": "C201",
        "stop_name": "Michigan Union, S. Univ",
        "stop_desc": "across from Law Quad at Art Museum",
        "stop_lat": 42.274988,
        "stop_lon": -83.740141,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "C202",
        "stop_code": "C202",
        "stop_name": "Shapiro Library",
        "stop_desc": "N side of S University E of Tappan",
        "stop_lat": 42.275051,
        "stop_lon": -83.737589,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "C203",
        "stop_code": "C203",
        "stop_name": "East Quad, Willard",
        "stop_desc": "Willard at E University",
        "stop_lat": 42.273793,
        "stop_lon": -83.735526,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "C208",
        "stop_code": "C208",
        "stop_name": "Kraus Building",
        "stop_desc": "S side of N University at Kraus Bldg",
        "stop_lat": 42.278488,
        "stop_lon": -83.738729,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "C210",
        "stop_code": "C210",
        "stop_name": "Power Center",
        "stop_desc": "Fletxher St at E Huron St",
        "stop_lat": 42.280851,
        "stop_lon": -83.737094,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "C211",
        "stop_code": "C211",
        "stop_name": "Rackham Bldg",
        "stop_desc": "Fletcher St at Washington St",
        "stop_lat": 42.280635,
        "stop_lon": -83.737273,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "C250",
        "stop_code": "C250",
        "stop_name": "Central Campus Transit Center: Chemistry",
        "stop_desc": "S side of Central Campus Transit Center",
        "stop_lat": 42.277682,
        "stop_lon": -83.734936,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "C251",
        "stop_code": "C251",
        "stop_name": "Central Campus Transit Center: Ruthven Museum",
        "stop_desc": "N side of Central Campus Transit Center",
        "stop_lat": 42.278176,
        "stop_lon": -83.735084,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "E601",
        "stop_code": "E601",
        "stop_name": "Green Rd Park & Ride Outbound",
        "stop_desc": "E side of service island in Green Rd Park and Ride lot",
        "stop_lat": 42.300154,
        "stop_lon": -83.693166,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "E603",
        "stop_code": "E603",
        "stop_name": "Michigan House",
        "stop_desc": "At the driveway to Michigan House on the N side of Commonwealth Blvd",
        "stop_lat": 42.30828,
        "stop_lon": -83.695795,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "E604",
        "stop_code": "E604",
        "stop_name": "2101 Commonwealth",
        "stop_desc": "2101 Commonwealth, in parking lot",
        "stop_lat": 42.30631,
        "stop_lon": -83.696538,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "E605",
        "stop_code": "E605",
        "stop_name": "Rachel Upjohn Building",
        "stop_desc": "Front entrance to Rachel Upjohn Bldg and Depression Center",
        "stop_lat": 42.307907,
        "stop_lon": -83.675536,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "E606",
        "stop_code": "E606",
        "stop_name": "East Ann Arbor Health & Geriatrics Center",
        "stop_desc": "Main entrance to East Ann Arbor Health and Geriatrics Center, under overhang",
        "stop_lat": 42.308185,
        "stop_lon": -83.673986,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "E607",
        "stop_code": "E607",
        "stop_name": "Arbor Lakes",
        "stop_desc": "Main entrance to Arbor Lakes facility, inside circle driveway",
        "stop_lat": 42.310883,
        "stop_lon": -83.6767,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "E608",
        "stop_code": "E608",
        "stop_name": "Domino's Farms Lobby A",
        "stop_desc": "W entrance to Dominos Farms Lobby A",
        "stop_lat": 42.314887,
        "stop_lon": -83.683234,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "E609",
        "stop_code": "E609",
        "stop_name": "Domino's Farms Lobby C",
        "stop_desc": "W entrance to Dominos Farms Lobby C",
        "stop_lat": 42.315938,
        "stop_lon": -83.683264,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "E610",
        "stop_code": "E610",
        "stop_name": "Domino's Farms Lobby M",
        "stop_desc": "E entrance to Dominos Farms Lobby M",
        "stop_lat": 42.32114,
        "stop_lon": -83.682196,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "E611",
        "stop_code": "E611",
        "stop_name": "Domino's Farms Lobby H",
        "stop_desc": "E entrance to Dominos Farms Lobby H (Main entrance to Dominos Farms)",
        "stop_lat": 42.318142,
        "stop_lon": -83.6821,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "E612",
        "stop_code": "E612",
        "stop_name": "Plymouth Park-and-Ride",
        "stop_desc": "Plymouth Rd AAATA Park-and-Ride at US-23",
        "stop_lat": 42.30597,
        "stop_lon": -83.68852,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "M302",
        "stop_code": "M302",
        "stop_name": "Stockwell Hall Inbound",
        "stop_desc": "W side of Observatory at Stockwell Hall",
        "stop_lat": 42.278494,
        "stop_lon": -83.731104,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "M303",
        "stop_code": "M303",
        "stop_name": "Cardiovascular Center",
        "stop_desc": "E side of Observatory at Ann St",
        "stop_lat": 42.281798,
        "stop_lon": -83.731002,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "M304",
        "stop_code": "M304",
        "stop_name": "Lloyd/Observatory",
        "stop_desc": "W side of Observatory at Ann St",
        "stop_lat": 42.281996,
        "stop_lon": -83.731232,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "M305",
        "stop_code": "M305",
        "stop_name": "Couzens Hall",
        "stop_desc": "SE corner of Ann St and Zina Pitcher",
        "stop_lat": 42.282236,
        "stop_lon": -83.733276,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "M306",
        "stop_code": "M306",
        "stop_name": "Zina Pitcher",
        "stop_desc": "E side of Zina Pitcher between Ann St and Catherine St",
        "stop_lat": 42.282695,
        "stop_lon": -83.73344,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "M307",
        "stop_code": "M307",
        "stop_name": "Biomedical Science Research Bldg",
        "stop_desc": "W side of Zina Pitcher between Ann St and Washtenaw",
        "stop_lat": 42.281984,
        "stop_lon": -83.733638,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "M309",
        "stop_code": "M309",
        "stop_name": "Glen/Catherine Outbound",
        "stop_desc": "NE corner of Catherine St and Glen Ave",
        "stop_lat": 42.283383,
        "stop_lon": -83.73551,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "M311",
        "stop_code": "M311",
        "stop_name": "North Ingalls Bldg",
        "stop_desc": "E side of North Ingalls, N of Catherine St",
        "stop_lat": 42.283524,
        "stop_lon": -83.738434,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "M312",
        "stop_code": "M312",
        "stop_name": "Medical Science Research Bldg II",
        "stop_desc": "N side of West Medical Center Dr at Medical Sciences Bldg driveway",
        "stop_lat": 42.284965,
        "stop_lon": -83.734687,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "M313",
        "stop_code": "M313",
        "stop_name": "Markley Hall",
        "stop_desc": "Across from Mott Hospital at Mary Markley Hall",
        "stop_lat": 42.281347,
        "stop_lon": -83.728011,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "M314",
        "stop_code": "M314",
        "stop_name": "Mott Hospital",
        "stop_desc": "N side of E Medical Center Dr at P4 parking structure, W of Mott Hospital",
        "stop_lat": 42.281505,
        "stop_lon": -83.728982,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "M315",
        "stop_code": "M315",
        "stop_name": "Taubman Outbound",
        "stop_desc": "E Medical Center Dr across from UM Hospital Main Entrance",
        "stop_lat": 42.283749,
        "stop_lon": -83.726923,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 1
      },
      {
        "stop_id": "M316",
        "stop_code": "M316",
        "stop_name": "Taubman Inbound",
        "stop_desc": "E Medical Center Dr at UM Hospital Main Entrance",
        "stop_lat": 42.284023,
        "stop_lon": -83.727306,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "M317",
        "stop_code": "M317",
        "stop_name": "Cancer Center Inbound",
        "stop_desc": "S side of E Medical Center Dr, E of Cancer Center Circle Dr",
        "stop_lat": 42.285271,
        "stop_lon": -83.730914,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "M319",
        "stop_code": "M319",
        "stop_name": "Cancer Center Outbound",
        "stop_desc": "N side of E Medical Center Dr, W of Cancer Center Circle Dr",
        "stop_lat": 42.285544,
        "stop_lon": -83.731538,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "M321",
        "stop_code": "M321",
        "stop_name": "Maiden Lane",
        "stop_desc": "NW corner of Maiden Ln Ct at Wall St",
        "stop_lat": 42.287583,
        "stop_lon": -83.734128,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "M323",
        "stop_code": "M323",
        "stop_name": "Wall St Structure",
        "stop_desc": "Wall St parking structure across from Kellogg Eye Center",
        "stop_lat": 42.288483,
        "stop_lon": -83.735965,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "M324",
        "stop_code": "M324",
        "stop_name": "VA Hospital Circle Drive",
        "stop_desc": "Stop near VA Hospital Main entrance",
        "stop_lat": 42.286465,
        "stop_lon": -83.71397,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "M350",
        "stop_code": "M350",
        "stop_name": "Fuller Rd at Mitchell Field, Lot M-75",
        "stop_desc": "Fuller Rd stop between entrances to M-75, S side of Fuller Rd",
        "stop_lat": 42.287108,
        "stop_lon": -83.723331,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "M351",
        "stop_code": "M351",
        "stop_name": "Lot M-75, Mitchell Field, Outbound (2)",
        "stop_desc": "Inside lot M-75 at Mitchell Field, E of E driveway",
        "stop_lat": 42.286812,
        "stop_lon": -83.723014,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "M352",
        "stop_code": "M352",
        "stop_name": "Lot M-75, Mitchell Field, Inbound (1)",
        "stop_desc": "Inside Lot M-75 at Mitchell Field, W of E driveway",
        "stop_lat": 42.286892,
        "stop_lon": -83.722684,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "M353",
        "stop_code": "M353",
        "stop_name": "Lot M-75, Mitchell Field, Inbound (2)",
        "stop_desc": "Inside Lot M-75 at Mitchell Field, E of Cedar Bend Driveway",
        "stop_lat": 42.286828,
        "stop_lon": -83.723778,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "M354",
        "stop_code": "M354",
        "stop_name": "Lot M-75, Mitchell Field, Outbound (1)",
        "stop_desc": "Inside lot M-75, W of Cedar Bend Dr",
        "stop_lat": 42.286763,
        "stop_lon": -83.723939,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N400",
        "stop_code": "N400",
        "stop_name": "VA Hospital, Fuller Rd",
        "stop_desc": "On Fuller Rd between Glazier Way and Beal Ave",
        "stop_lat": 42.2875,
        "stop_lon": -83.71254,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N401",
        "stop_code": "N401",
        "stop_name": "Biomedical Engineering Bldg",
        "stop_desc": "W side of Beal at Biomedical Engineering Bldg",
        "stop_lat": 42.288535,
        "stop_lon": -83.713062,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N402",
        "stop_code": "N402",
        "stop_name": "Ford Presidential Library",
        "stop_desc": "E side of Beal at Gerald R Ford Presidential Library",
        "stop_lat": 42.288514,
        "stop_lon": -83.712909,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N403",
        "stop_code": "N403",
        "stop_name": "Cooley Lab Inbound",
        "stop_desc": "N side of Bonisteel, W of Beal",
        "stop_lat": 42.290454,
        "stop_lon": -83.7142,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N404",
        "stop_code": "N404",
        "stop_name": "Cooley Lab Outbound",
        "stop_desc": "S side of Bonisteel, W of Beal",
        "stop_lat": 42.290211,
        "stop_lon": -83.71375,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N405",
        "stop_code": "N405",
        "stop_name": "FXB Inbound",
        "stop_desc": "W side of Beal at Hayward",
        "stop_lat": 42.293481,
        "stop_lon": -83.712643,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N406",
        "stop_code": "N406",
        "stop_name": "FXB Outbound",
        "stop_desc": "E side of Beal at Hayward",
        "stop_lat": 42.293572,
        "stop_lon": -83.71252,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N414",
        "stop_code": "N414",
        "stop_name": "Northwood III Outbound",
        "stop_desc": "S side of Hubbard at Northwood III, across from lot NW 10",
        "stop_lat": 42.294869,
        "stop_lon": -83.717922,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N416",
        "stop_code": "N416",
        "stop_name": "Northwood I Outbound",
        "stop_desc": "S side of Hubbard, W of Cram Circle",
        "stop_lat": 42.29499,
        "stop_lon": -83.714997,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N418",
        "stop_code": "N418",
        "stop_name": "Cram Circle Outbound",
        "stop_desc": "E side of Cram Circle, N of Hubbard",
        "stop_lat": 42.296564,
        "stop_lon": -83.715131,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N420",
        "stop_code": "N420",
        "stop_name": "Northwood II Outbound",
        "stop_desc": "S side of Bishop, W of Beal",
        "stop_lat": 42.297772,
        "stop_lon": -83.712708,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N421",
        "stop_code": "N421",
        "stop_name": "Fire Station Inbound",
        "stop_desc": "Firestation driveway at bus shelter",
        "stop_lat": 42.299847,
        "stop_lon": -83.712484,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N424",
        "stop_code": "N424",
        "stop_name": "Plymouth Rd Crosswalk",
        "stop_desc": "S side of McIntyre, Northwood IV, lot NW 44",
        "stop_lat": 42.301442,
        "stop_lon": -83.709615,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N426",
        "stop_code": "N426",
        "stop_name": "Northwood IV",
        "stop_desc": "W side of McIntyre at lot NW 46",
        "stop_lat": 42.298682,
        "stop_lon": -83.709545,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N428",
        "stop_code": "N428",
        "stop_name": "Northwood Community Center",
        "stop_desc": "W side of McIntyre, across from NW Community Ctr at lot NW 47",
        "stop_lat": 42.297335,
        "stop_lon": -83.709671,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N429",
        "stop_code": "N429",
        "stop_name": "Hayward/Hubbard, Hubbard Inbound",
        "stop_desc": "N side of Hubbard, east of Hayward/Hubbard intersection",
        "stop_lat": 42.295681,
        "stop_lon": -83.707214,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N430",
        "stop_code": "N430",
        "stop_name": "Hayward/Hubbard, Hubbard Outbound",
        "stop_desc": "W side of Hubbard, N of Hayward/Hubbard intersection",
        "stop_lat": 42.295877,
        "stop_lon": -83.707689,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N431",
        "stop_code": "N431",
        "stop_name": "Huron/Hubbard, Hubbard Inbound",
        "stop_desc": "N side of Hubbard, W of Huron Pkwy",
        "stop_lat": 42.295495,
        "stop_lon": -83.705336,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N432",
        "stop_code": "N432",
        "stop_name": "Hayward/Hubbard, Hayward Outbound",
        "stop_desc": "S side of Hayward, W of Hayward/Hubbard intersection",
        "stop_lat": 42.295433,
        "stop_lon": -83.707682,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N433",
        "stop_code": "N433",
        "stop_name": "NCAC, Hubbard Inbound",
        "stop_desc": "N side of Hubbard at NCAC, lot NC 65",
        "stop_lat": 42.295128,
        "stop_lon": -83.70305,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N434",
        "stop_code": "N434",
        "stop_name": "Huron/Hubbard, Huron Outbound",
        "stop_desc": "W side of Huron Pkwy, S of Hubbard",
        "stop_lat": 42.295187,
        "stop_lon": -83.704939,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N435",
        "stop_code": "N435",
        "stop_name": "Northwood V (1)",
        "stop_desc": "Northwood V, W side of Stone Rd at Hubbard Rd",
        "stop_lat": 42.294566,
        "stop_lon": -83.700368,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N436",
        "stop_code": "N436",
        "stop_name": "Northwood V (2)",
        "stop_desc": "Northwood V, Stone Rd between NW 53 and NW 54",
        "stop_lat": 42.293271,
        "stop_lon": -83.699099,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N440",
        "stop_code": "N440",
        "stop_name": "NCRC, SB Huron Pkwy",
        "stop_desc": "NCRC, E side of Huron Pkwy, S of Plymouth",
        "stop_lat": 42.30079,
        "stop_lon": -83.704566,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N441",
        "stop_code": "N441",
        "stop_name": "NCRC, NB Huron Pkwy",
        "stop_desc": "NCRC, E side of Huron Pkwy, S of Plymouth",
        "stop_lat": 42.300427,
        "stop_lon": -83.704166,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N442",
        "stop_code": "N442",
        "stop_name": "NCAC, Inbound",
        "stop_desc": "Lot NC 65, N side of NCAC complex (WBD)",
        "stop_lat": 42.296868,
        "stop_lon": -83.702388,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N443",
        "stop_code": "N443",
        "stop_name": "NCAC, Outbound",
        "stop_desc": "Lot NC 65, N side of NCAC complex (EBD)",
        "stop_lat": 42.296939,
        "stop_lon": -83.702479,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N444",
        "stop_code": "N444",
        "stop_name": "North Campus Facilities Services Bldg, Outbound",
        "stop_desc": "S side of Baxter Rd across from maintenance facility",
        "stop_lat": 42.297861,
        "stop_lon": -83.697351,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N445",
        "stop_code": "N445",
        "stop_name": "North Campus Facilities Services Bldg, Inbound",
        "stop_desc": "N side of Baxter at Maintenance Facility",
        "stop_lat": 42.297949,
        "stop_lon": -83.697367,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N446",
        "stop_code": "N446",
        "stop_name": "NCRC",
        "stop_desc": "NCRC at Building 18",
        "stop_lat": 42.301063,
        "stop_lon": -83.705668,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N452",
        "stop_code": "N452",
        "stop_name": "Fuller Rd at Lot NC-78, Mitchell Field (3)",
        "stop_desc": "W stop on N side of Fuller Rd at NC 78",
        "stop_lat": 42.287276,
        "stop_lon": -83.722974,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N500",
        "stop_code": "N500",
        "stop_name": "Glazier Way, Lot NC-51, West",
        "stop_desc": "Glazier Way (NC 51) first stop on W side of lot",
        "stop_lat": 42.288854,
        "stop_lon": -83.706097,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N501",
        "stop_code": "N501",
        "stop_name": "Glazier Way, Lot NC-51, North",
        "stop_desc": "Glazier Way (NC 51) second stop on N side of lot",
        "stop_lat": 42.289806,
        "stop_lon": -83.705105,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N502",
        "stop_code": "N502",
        "stop_name": "Glazier Way, Lot NC-51, East",
        "stop_desc": "Glazier Way (NC 51) third stop on E side of lot",
        "stop_lat": 42.288703,
        "stop_lon": -83.704971,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N550",
        "stop_code": "N550",
        "stop_name": "Pierpont Commons, Murfin Outbound",
        "stop_desc": "NE corner of Murfin and Bonisteel, on Murfin",
        "stop_lat": 42.290818,
        "stop_lon": -83.718419,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N552",
        "stop_code": "N552",
        "stop_name": "Art & Architecture",
        "stop_desc": "SE corner of Bonisteel and Murfin",
        "stop_lat": 42.290206,
        "stop_lon": -83.717752,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "N553",
        "stop_code": "N553",
        "stop_name": "Pierpont Commons, Bonisteel Inbound",
        "stop_desc": "NE corner of Murfin and Bonisteel, on Bonisteel",
        "stop_lat": 42.290425,
        "stop_lon": -83.718151,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "S001",
        "stop_code": "S001",
        "stop_name": "Crisler Center/Lot SC-7",
        "stop_desc": "glass shelter between Crisler Lots SC-5 and SC-7",
        "stop_lat": 42.264356,
        "stop_lon": -83.744354,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "S003",
        "stop_code": "S003",
        "stop_name": "Transportation Gate",
        "stop_desc": "back door to Transit Services Bldg",
        "stop_lat": 42.266381,
        "stop_lon": -83.745282,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "S004",
        "stop_code": "S004",
        "stop_name": "Facilities Services Building",
        "stop_desc": "SE corner of Kipke and Greene",
        "stop_lat": 42.268068,
        "stop_lon": -83.747307,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "S005",
        "stop_code": "S005",
        "stop_name": "Institute for Continuing Legal Education",
        "stop_desc": "W side of Greene bteween Hoover and Kipke",
        "stop_lat": 42.268515,
        "stop_lon": -83.747545,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "S006",
        "stop_code": "S006",
        "stop_name": "Greene/Hoover",
        "stop_desc": "E side of Greene St at Hoover",
        "stop_lat": 42.269279,
        "stop_lon": -83.747427,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "S007",
        "stop_code": "S007",
        "stop_name": "Intramural Building Outbound",
        "stop_desc": "S side of Hoover between Division and Sybil",
        "stop_lat": 42.269587,
        "stop_lon": -83.743371,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "S008",
        "stop_code": "S008",
        "stop_name": "Intramural Building Inbound",
        "stop_desc": "N side of Hoover between Sybil and Division",
        "stop_lat": 42.269671,
        "stop_lon": -83.743343,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "S002",
        "stop_code": "S002",
        "stop_name": "Crisler Center Lot SC-5",
        "stop_desc": "N side of Kipke Drive between Campus Safety and Transportation Services",
        "stop_lat": 42.26583,
        "stop_lon": -83.745127,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "S009",
        "stop_code": "S009",
        "stop_name": "Law Quad",
        "stop_desc": "E side of NBD State at Monroe St",
        "stop_lat": 42.273502,
        "stop_lon": -83.740641,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "S010",
        "stop_code": "S010",
        "stop_name": "South Quad",
        "stop_desc": "W side of SBD State past Monroe St",
        "stop_lat": 42.273052,
        "stop_lon": -83.740726,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      },
      {
        "stop_id": "M322",
        "stop_code": "M322",
        "stop_name": "W Medical Ctr Dr at Catherine",
        "stop_desc": "E side of West Medical Center Drive N of Catherine at Medical School",
        "stop_lat": 42.283541,
        "stop_lon": -83.735342,
        "zone_id": "",
        "stop_url": "",
        "location_type": "",
        "parent_station": "",
        "stop_timezone": "",
        "wheelchair_boarding": 2
      }
    ],
    stop_times: [
      {
        "trip_id": 42392,
        "arrival_time": "8:30:00",
        "departure_time": "8:30:00",
        "stop_id": "S001",
        "stop_sequence": 1,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": ""
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:30:56",
        "departure_time": "8:30:56",
        "stop_id": "S003",
        "stop_sequence": 2,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 0.2655
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:31:57",
        "departure_time": "8:31:57",
        "stop_id": "S004",
        "stop_sequence": 3,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 0.5514
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:32:29",
        "departure_time": "8:32:29",
        "stop_id": "S006",
        "stop_sequence": 4,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 0.7054
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:33:44",
        "departure_time": "8:33:44",
        "stop_id": "S007",
        "stop_sequence": 5,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 1.0604
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:36:04",
        "departure_time": "8:36:04",
        "stop_id": "S009",
        "stop_sequence": 6,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 1.7167
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:36:43",
        "departure_time": "8:36:43",
        "stop_id": "C200",
        "stop_sequence": 7,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 1.9018
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:38:40",
        "departure_time": "8:38:40",
        "stop_id": "C208",
        "stop_sequence": 8,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 2.4518
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:40:00",
        "departure_time": "8:40:00",
        "stop_id": "C250",
        "stop_sequence": 9,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 2.8058
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:41:00",
        "departure_time": "8:41:00",
        "stop_id": "M305",
        "stop_sequence": 10,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 3.5127
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:43:06",
        "departure_time": "8:43:06",
        "stop_id": "M313",
        "stop_sequence": 11,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 4.0465
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:44:37",
        "departure_time": "8:44:37",
        "stop_id": "M315",
        "stop_sequence": 12,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 4.4339
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:46:31",
        "departure_time": "8:46:31",
        "stop_id": "M319",
        "stop_sequence": 13,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 4.9184
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:50:02",
        "departure_time": "8:50:02",
        "stop_id": "M350",
        "stop_sequence": 14,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 5.8089
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:53:04",
        "departure_time": "8:53:04",
        "stop_id": "N552",
        "stop_sequence": 15,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 6.5789
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:54:22",
        "departure_time": "8:54:22",
        "stop_id": "N404",
        "stop_sequence": 16,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 6.9081
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:56:18",
        "departure_time": "8:56:18",
        "stop_id": "N406",
        "stop_sequence": 17,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 7.3987
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:58:16",
        "departure_time": "8:58:16",
        "stop_id": "N432",
        "stop_sequence": 18,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 7.9002
      },
      {
        "trip_id": 42392,
        "arrival_time": "8:59:17",
        "departure_time": "8:59:17",
        "stop_id": "N434",
        "stop_sequence": 19,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 8.1599
      },
      {
        "trip_id": 42392,
        "arrival_time": "9:03:58",
        "departure_time": "9:03:58",
        "stop_id": "N500",
        "stop_sequence": 20,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 9.3464
      },
      {
        "trip_id": 42392,
        "arrival_time": "9:05:00",
        "departure_time": "9:05:00",
        "stop_id": "N501",
        "stop_sequence": 21,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 9.5893
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:30:00",
        "departure_time": "6:30:00",
        "stop_id": "N501",
        "stop_sequence": 1,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": ""
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:30:28",
        "departure_time": "6:30:28",
        "stop_id": "N502",
        "stop_sequence": 2,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 0.1314
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:33:20",
        "departure_time": "6:33:20",
        "stop_id": "N400",
        "stop_sequence": 3,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 0.915
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:35:00",
        "departure_time": "6:35:00",
        "stop_id": "N403",
        "stop_sequence": 4,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 1.3613
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:35:34",
        "departure_time": "6:35:34",
        "stop_id": "N553",
        "stop_sequence": 5,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 1.6854
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:37:00",
        "departure_time": "6:37:00",
        "stop_id": "M352",
        "stop_sequence": 6,
        "stop_headsign": "",
        "pickup_type": 1,
        "drop_off_type": 1,
        "shape_dist_traveled": 2.4871
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:37:10",
        "departure_time": "6:37:10",
        "stop_id": "M353",
        "stop_sequence": 7,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 2.5627
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:39:25",
        "departure_time": "6:39:25",
        "stop_id": "M317",
        "stop_sequence": 8,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 3.518
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:40:19",
        "departure_time": "6:40:19",
        "stop_id": "M316",
        "stop_sequence": 9,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 3.9052
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:41:30",
        "departure_time": "6:41:30",
        "stop_id": "M314",
        "stop_sequence": 10,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 4.412
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:42:01",
        "departure_time": "6:42:01",
        "stop_id": "M303",
        "stop_sequence": 11,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 4.631
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:42:48",
        "departure_time": "6:42:48",
        "stop_id": "M307",
        "stop_sequence": 12,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 4.9645
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:43:52",
        "departure_time": "6:43:52",
        "stop_id": "C211",
        "stop_sequence": 13,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 5.4209
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:45:00",
        "departure_time": "6:45:00",
        "stop_id": "C250",
        "stop_sequence": 14,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 5.8711
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:47:42",
        "departure_time": "6:47:42",
        "stop_id": "C203",
        "stop_sequence": 15,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 6.414
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:49:11",
        "departure_time": "6:49:11",
        "stop_id": "C202",
        "stop_sequence": 16,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 6.7131
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:50:13",
        "departure_time": "6:50:13",
        "stop_id": "C201",
        "stop_sequence": 17,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 6.9222
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:51:31",
        "departure_time": "6:51:31",
        "stop_id": "S010",
        "stop_sequence": 18,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 7.1843
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:54:31",
        "departure_time": "6:54:31",
        "stop_id": "S008",
        "stop_sequence": 19,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 7.7876
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:56:43",
        "departure_time": "6:56:43",
        "stop_id": "S005",
        "stop_sequence": 20,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 8.2296
      },
      {
        "trip_id": 42559,
        "arrival_time": "6:58:47",
        "departure_time": "6:58:47",
        "stop_id": "S002",
        "stop_sequence": 21,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 8.6457
      },
      {
        "trip_id": 42559,
        "arrival_time": "7:00:00",
        "departure_time": "7:00:00",
        "stop_id": "S001",
        "stop_sequence": 22,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 8.879
      },
      {
        "trip_id": 42719,
        "arrival_time": "5:20:00",
        "departure_time": "5:20:00",
        "stop_id": "M353",
        "stop_sequence": 1,
        "stop_headsign": "",
        "pickup_type": 1,
        "drop_off_type": 1,
        "shape_dist_traveled": ""
      },
      {
        "trip_id": 42719,
        "arrival_time": "5:21:56",
        "departure_time": "5:21:56",
        "stop_id": "M317",
        "stop_sequence": 2,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 0.9412
      },
      {
        "trip_id": 42719,
        "arrival_time": "5:22:43",
        "departure_time": "5:22:43",
        "stop_id": "M316",
        "stop_sequence": 3,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 1.3239
      },
      {
        "trip_id": 42719,
        "arrival_time": "5:23:45",
        "departure_time": "5:23:45",
        "stop_id": "M314",
        "stop_sequence": 4,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 1.8303
      },
      {
        "trip_id": 42719,
        "arrival_time": "5:24:12",
        "departure_time": "5:24:12",
        "stop_id": "M303",
        "stop_sequence": 5,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 2.0493
      },
      {
        "trip_id": 42719,
        "arrival_time": "5:25:00",
        "departure_time": "5:25:00",
        "stop_id": "M307",
        "stop_sequence": 6,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 2.4259
      },
      {
        "trip_id": 43415,
        "arrival_time": "19:30:00",
        "departure_time": "19:30:00",
        "stop_id": "M306",
        "stop_sequence": 1,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": ""
      },
      {
        "trip_id": 43415,
        "arrival_time": "19:30:40",
        "departure_time": "19:30:40",
        "stop_id": "M322",
        "stop_sequence": 2,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 0.2395
      },
      {
        "trip_id": 43415,
        "arrival_time": "19:31:09",
        "departure_time": "19:31:09",
        "stop_id": "M312",
        "stop_sequence": 3,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 0.4188
      },
      {
        "trip_id": 43415,
        "arrival_time": "19:34:18",
        "departure_time": "19:34:18",
        "stop_id": "M350",
        "stop_sequence": 4,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 1.5515
      },
      {
        "trip_id": 43415,
        "arrival_time": "19:36:58",
        "departure_time": "19:36:58",
        "stop_id": "N402",
        "stop_sequence": 5,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 2.5114
      },
      {
        "trip_id": 43415,
        "arrival_time": "19:38:43",
        "departure_time": "19:38:43",
        "stop_id": "N406",
        "stop_sequence": 6,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 3.1425
      },
      {
        "trip_id": 43415,
        "arrival_time": "19:40:06",
        "departure_time": "19:40:06",
        "stop_id": "N432",
        "stop_sequence": 7,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 3.644
      },
      {
        "trip_id": 43415,
        "arrival_time": "19:42:29",
        "departure_time": "19:42:29",
        "stop_id": "N441",
        "stop_sequence": 8,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 4.4997
      },
      {
        "trip_id": 43415,
        "arrival_time": "19:45:00",
        "departure_time": "19:45:00",
        "stop_id": "N446",
        "stop_sequence": 9,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 5.3826
      },
      {
        "trip_id": 43415,
        "arrival_time": "19:46:42",
        "departure_time": "19:46:42",
        "stop_id": "N443",
        "stop_sequence": 10,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 6.131
      },
      {
        "trip_id": 43415,
        "arrival_time": "19:48:00",
        "departure_time": "19:48:00",
        "stop_id": "N444",
        "stop_sequence": 11,
        "stop_headsign": "",
        "pickup_type": 0,
        "drop_off_type": 0,
        "shape_dist_traveled": 6.6963
      }
    ]
  };
}
